/*
Project: Telecom Customer Churn Analysis

Domain: Telecommunications (Telecom Industry)

Dataset: IBM Telco Customer Churn Dataset

Dataset Link: https://www.kaggle.com/datasets/blastchar/telco-customer-churn?utm_source=chatgpt.com

Objective: To analyze customer churn behavior, identify factors contributing to customer attrition, 
           evaluate revenue impact, segment customers based on value and risk, and generate actionable 
		   insights to improve customer retention and business profitability.


End Consumer: Customer Retention Team

Perspective: 'Customer Retention & Revenue Analytics'

Tools used: SQL Tools

Key Analysis Performed:
-- 10 KPIs
   10 Easy problems
   10 Medium problems
   10 Difficult problems
   10 Univariate problems
   10 Bivariate problems
   10 Multivariate problems
   10 CTE related problems
   10 Window functions related problems
   */
-- ======================================

-- 10 KPIs
-- =========================================
-- 1. Overall churn rate.
-- =========================================
-- Columns used: Churn,CustomerID
-- Query:
   SELECT 
       SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 1.0 / COUNT(*) AS churn_rate
   FROM customer_churn;
-- =========================================

-- 2. Customer retention rate.
-- =========================================
-- Columns used: Churn,CustomerID
-- Query:
   SELECT 
     (SUM(CASE WHEN Churn = 'No' THEN 1 ELSE 0 END) * 1.0 / COUNT(CustomerID)) AS retention_rate
   FROM customer_churn;
-- =========================================

-- 3. Total revenue generated by the company.
-- =========================================
-- Columns used: TotalCharges
-- Query:
   SELECT
        SUM(TotalCharges) AS total_revenue
   FROM customer_churn;
-- =========================================

-- =========================================
-- 4. Revenue generated by churned customers.
-- =========================================
-- Columns used: Churn,TotalCharges
-- Query:
    SELECT
        SUM(TRY_CAST(NULLIF(LTRIM(RTRIM(TotalCharges)), '') AS DECIMAL(10,2))) AS churned_revenue
    FROM customer_churn
    WHERE Churn = 'Yes';
-- =========================================

-- =========================================
-- 5. Average customer tenure.
-- =========================================
-- Columns used: Tenure
-- Query:
   SELECT 
        AVG(Tenure) AS avg_tenure
   FROM customer_churn;
-- =========================================

-- ========================================= 
-- 6. Average monthly revenue per customer.
-- =========================================
-- Columns used: MonthlyCharges
-- Query:
   SELECT 
       AVG(MonthlyCharges) AS avg_monthly_revenue
   FROM customer_churn;
-- =========================================

-- =========================================
-- 7. Average lifetime revenue per customer.
-- =========================================
-- Columns used: TotalCharges
-- Query:
   SELECT
        AVG(TotalCharges) AS avg_lifetime_revenue
   FROM customer_churn;
-- =========================================

-- =========================================
-- 8. Churn rate among Fiber Optic customers.
-- =========================================
-- Columns used: InternetService,Churn
-- Query:
   SELECT 
       SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 1.0 / COUNT(*) AS fiber_churn_rate
   FROM customer_churn
   WHERE InternetService = 'Fiber optic';
-- =========================================

-- =========================================
-- 9. Percentage of customers use Tech Support services.
-- =========================================
-- Columns used: TechSupport,CustomerID
-- Query:
   SELECT 
      SUM(CASE WHEN TechSupport = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)
      AS tech_support_percentage
   FROM customer_churn;
--- =========================================

-- =========================================
-- 10. Percentage of customers on Month-to-Month contracts.
-- =========================================
-- Columns used: Contract
-- Query:
   SELECT 
       SUM(CASE WHEN Contract = 'Month-to-month' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)
       AS month_to_month_percentage
   FROM customer_churn;
-- =========================================


-- SECTION 2: Easy Problems
-- ==========================================
--1. Total number of customers.
-- ==========================================
-- Columns used: CustomerID
-- Query:
   SELECT COUNT(CustomerID) AS total_customers
   FROM customer_churn;
-- ==========================================

-- ==========================================
-- 2. Total number of churned customers.
-- ==========================================
-- Columns used: Churn
-- Query:
   SELECT COUNT(*) AS churned_customers
   FROM customer_churn
   WHERE Churn = 'Yes';
-- ==========================================

-- ==========================================
-- 3. Total number of retained customers.
-- ==========================================
-- Columns used: Churn
-- Query:
   SELECT COUNT(*) AS retained_customers
   FROM customer_churn
   WHERE Churn = 'No';
-- ==========================================

-- ==========================================
-- 4. All distinct contract types.
-- ==========================================
-- Columns used: Contract
-- Query:
   SELECT DISTINCT Contract
   FROM customer_churn;
-- ==========================================

-- ==========================================
-- 5. All distinct payment methods.
-- ==========================================
-- Columns used: PaymentMethod
-- Query:
   SELECT DISTINCT PaymentMethod
   FROM customer_churn;
-- ==========================================

-- ==========================================
-- 6. Top 10 customers with the highest total charges.
-- ==========================================
-- Columns used: CustomerID,TotalCharges
-- Query:
   SELECT TOP 10
       CustomerID,
       TRY_CAST(TotalCharges AS DECIMAL(10,2)) AS TotalCharges
   FROM customer_churn
   ORDER BY TRY_CAST(TotalCharges AS DECIMAL(10,2)) DESC;
-- ==========================================

-- ==========================================
-- 7. Top 10 customers with the longest tenure.
-- ==========================================
-- Columns used: CustomerID,Tenure
-- Query:
   SELECT TOP 10
          CustomerID,
          Tenure
   FROM customer_churn
   ORDER BY Tenure DESC;
-- ==========================================

-- ==========================================
-- 8. Customers using Fiber Optic internet service.
-- ==========================================
-- Columns used: CustomerID,InternetService
-- Query:
   SELECT CustomerID,
          InternetService
   FROM customer_churn
   WHERE InternetService = 'Fiber optic';
-- ==========================================

-- ==========================================
-- 9. Customers who have Tech Support.
-- ==========================================
-- Columns used: CustomerID,TechSupport
-- Query:
   SELECT CustomerID,
          TechSupport
   FROM customer_churn
   WHERE TechSupport = 'Yes';
-- ==========================================

-- ==========================================
-- 10. Customers whose monthly charges are greater than 100.
-- ==========================================
-- Columns used: CustomerID,MonthlyCharges
-- Query:
   SELECT CustomerID,
          MonthlyCharges
   FROM customer_churn
   WHERE MonthlyCharges > 100;
-- ==========================================


-- SECTION 3: Medium Problems
-- ==========================================
-- 1. Churn rate by gender.
-- ==========================================
-- Columns used: Gender,Churn
-- Query:
   SELECT Gender,
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
       *100.0/COUNT(*),2) AS churn_rate
   FROM customer_churn
   GROUP BY Gender;
-- ==========================================

-- ==========================================
-- 2. Churn rate by contract type.
-- ==========================================
-- Columns used: Contract,Churn
-- Query:
   SELECT Contract,
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
       *100.0/COUNT(*),2) AS churn_rate
   FROM customer_churn
   GROUP BY Contract;
-- ==========================================

-- ==========================================
-- 3. Churn rate by payment method.
-- ==========================================
-- Columns used: PaymentMethod,Churn
-- Query:
   SELECT PaymentMethod,
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
       *100.0/COUNT(*),2) AS churn_rate
   FROM customer_churn
   GROUP BY PaymentMethod;
-- ==========================================

-- ==========================================
-- 4. Average monthly charges by internet service type.
-- ==========================================
-- Columns used: InternetService,MonthlyCharges
-- Query:
   SELECT InternetService,
        ROUND(AVG(MonthlyCharges),2)
        AS avg_monthly_charges
   FROM customer_churn
   GROUP BY InternetService;
-- ==========================================

-- ==========================================
-- 5. Average tenure by contract type.
-- ==========================================
-- Columns used: Contract,Tenure
-- Query:
   SELECT Contract,
        ROUND(AVG(Tenure),2)
       AS avg_tenure
  FROM customer_churn
  GROUP BY Contract;
-- ==========================================

-- ==========================================
-- 6. Total revenue generated by each contract type.
-- ==========================================
-- Columns used: Contract,TotalCharges
-- Query:
   SELECT Contract,
        ROUND(
              SUM(TotalCharges),
              2
              ) AS total_revenue
   FROM customer_churn
   GROUP BY Contract;
-- ==========================================

-- ==========================================
-- 7. Contract types with more than 1000 customers.
-- ==========================================
-- Columns used: Contract,CustomerID
-- Query:
   SELECT Contract,
       COUNT(*) AS total_customers
   FROM customer_churn
   GROUP BY Contract
   HAVING COUNT(*) > 1000;
-- ==========================================

-- ==========================================
-- 8. Internet service types whose average monthly charges exceed the company average.
-- ==========================================
-- Columns used: InternetService,MonthlyCharges
-- Query:
   SELECT InternetService,
        ROUND(AVG(MonthlyCharges),2)
        AS avg_monthly_charges
   FROM customer_churn
   GROUP BY InternetService
   HAVING AVG(MonthlyCharges) >
   (
    SELECT AVG(MonthlyCharges)
   FROM customer_churn
   );
-- ==========================================

-- ==========================================
-- 9. Top 5 payment methods generating the highest revenue.
-- ==========================================
-- Columns used: PaymentMethod,TotalCharges
-- Query:
   SELECT TOP 5
        PaymentMethod,
        ROUND(
        SUM(TotalCharges)
        ,2)
       AS total_revenue
      FROM customer_churn
      GROUP BY PaymentMethod
      ORDER BY total_revenue DESC;
-- ==========================================

-- ==========================================
-- 10. Revenue lost due to churn for each contract type.
-- ==========================================
-- Columns used: Contract,Churn,TotalCharges
-- Query:
   SELECT Contract,
        ROUND(
        SUM(TotalCharges)
        ,2
       ) AS revenue_lost
   FROM customer_churn
   WHERE Churn='Yes'
 
   GROUP BY Contract;
-- ==========================================


-- SECTION 4: Difficult Problems
-- ==========================================
-- 1. High-revenue customers who churned.
-- ==========================================
-- Columns used: CustomerID,TotalCharges,Churn
-- Query:
    SELECT CustomerID,
           TotalCharges AS TotalCharges
    FROM customer_churn
 
    WHERE Churn='Yes'
 
    AND TotalCharges
    >
    (SELECT AVG(TotalCharges)FROM customer_churn)
    ORDER BY TotalCharges DESC;
-- ==========================================

-- ==========================================
-- 2. Customers whose total charges exceed the company average total charges.
-- ==========================================
-- Columns used: CustomerID,TotalCharges
-- Query:
   SELECT CustomerID,
       TotalCharges AS TotalCharges
   FROM customer_churn
 
   WHERE TotalCharges
   >
  (SELECT AVG(
  TotalCharges
  )
  FROM customer_churn
  );
-- ==========================================

-- ==========================================
-- 3. Customers whose total charges exceed the average total charges of their contract type.
-- ==========================================
-- Columns used: CustomerID,Contract,TotalCharges
-- Query:
    SELECT CustomerID,
        Contract,
        TotalCharges AS TotalCharges
 
    FROM customer_churn c1
 
    WHERE TotalCharges
    >
   (
   SELECT AVG(TotalCharges)
   FROM customer_churn c2
   WHERE c1.Contract = c2.Contract
   );
-- ==========================================

-- ==========================================
-- 4. Customers into value segments based on tenure and revenue.
-- ==========================================
-- Columns used: CustomerID,Tenure,TotalCharges
-- Query:
   SELECT CustomerID,
          Tenure,
          TotalCharges AS TotalCharges,
 
        CASE
             WHEN Tenure >= 48
                  AND TotalCharges >= 4000
             THEN 'High Value'
 
             WHEN Tenure >= 24
                  AND TotalCharges >= 2000
             THEN 'Medium Value'
              
             ELSE 'Low Value'
        END AS customer_segment
 
   FROM customer_churn;
-- ==========================================

-- ==========================================
-- 5. Customers into churn-risk segments based on tenure, contract type, and monthly charges.
-- ==========================================
-- Columns used: CustomerID,Tenure,Contract,MonthlyCharges
-- Query:
   SELECT CustomerID,
 
        CASE
     WHEN Contract='Month-to-month'
          AND Tenure < 12
          AND MonthlyCharges > 80
     THEN 'High Risk'
      
     WHEN Contract='Month-to-month'
          AND Tenure BETWEEN 12 AND 24
     THEN 'Medium Risk'
      
     WHEN Contract='One year'
     THEN 'Medium Risk'
      
     ELSE 'Low Risk'
     END AS churn_risk
      
    FROM customer_churn;
-- ==========================================

-- ==========================================
-- 6. Customers paying high monthly charges despite having low tenure.
-- ==========================================
-- Columns used: CustomerID,MonthlyCharges,Tenure
-- Query:
    SELECT CustomerID,
        MonthlyCharges,
        Tenure
 FROM customer_churn
 WHERE MonthlyCharges > 80
 AND Tenure < 12;
-- ==========================================

-- ==========================================
-- 7. Percentage contribution of each contract type to total revenue.
-- ==========================================
-- Columns used: Contract,TotalCharges
-- Query:
    SELECT Contract,
 
        ROUND(
        SUM(TotalCharges) * 100.0
        /
        (
        SELECT SUM(
               TotalCharges
               )
        FROM customer_churn
        )
        ,2
        ) AS revenue_contribution_pct
         
    FROM customer_churn
     
    GROUP BY Contract;
-- ==========================================

-- ==========================================
-- 8. Total revenue at risk due to customer churn.
-- ==========================================
-- Columns used: Churn,TotalCharges
-- Query:
    SELECT
     ROUND(
           SUM(TotalCharges),
           2
             ) AS lifetime_revenue_lost
    FROM customer_churn
    WHERE Churn = 'Yes';
-- ==========================================

-- ==========================================
-- 9. Churn rate of each contract type against the overall company churn rate.
-- ==========================================
-- Columns used: Contract,Churn
-- Query:
    SELECT Contract,
     
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS contract_churn_rate,
         
        (
        SELECT ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        )
        FROM customer_churn
        ) AS overall_churn_rate
         
     FROM customer_churn
      
     GROUP BY Contract;
-- =========================================

-- ==========================================
-- 10. Customer segments that generate high revenue but also experience high churn.
-- ==========================================
-- Columns used: Contract,Churn,TotalCharges
-- Query:
SELECT
    CASE
        WHEN TotalCharges >= 5000 THEN 'High Revenue'
        WHEN TotalCharges >= 2000 THEN 'Medium Revenue'
        ELSE 'Low Revenue'
    END AS revenue_segment,

    COUNT(*) AS total_customers,

    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS churn_rate,

    ROUND(SUM(TotalCharges), 2) AS total_revenue

FROM customer_churn

GROUP BY
    CASE
        WHEN TotalCharges >= 5000 THEN 'High Revenue'
        WHEN TotalCharges >= 2000 THEN 'Medium Revenue'
        ELSE 'Low Revenue'
    END

ORDER BY churn_rate DESC;
-- ==========================================

-- SECTION 5: Univariate Analysis
-- ==========================================
-- 1. Distribution of churn status.
-- ==========================================
-- Columns used: Churn
-- Query:
    SELECT Churn,
        COUNT(*) AS total_customers
    FROM customer_churn
    GROUP BY Churn;
-- ==========================================

-- ==========================================
-- 2. Distribution of contract types.
-- ==========================================
-- Columns used: Contract
-- Query:
   SELECT Contract,
        COUNT(*) AS total_customers
   FROM customer_churn
   GROUP BY Contract;
-- ==========================================

-- ==========================================
-- 3. Distribution of payment methods.
-- ==========================================
-- Columns used: PaymentMethod
-- Query:
   SELECT PaymentMethod,
        COUNT(*) AS total_customers
   FROM customer_churn
   GROUP BY PaymentMethod;
-- ==========================================

-- ==========================================
-- 4. Distribution of internet service types.
-- ==========================================
-- Columns used: InternetService
-- Query:
   SELECT InternetService,
        COUNT(*) AS total_customers
   FROM customer_churn
   GROUP BY InternetService;
-- ==========================================

-- ==========================================
-- 5. Distribution of customer tenure.
-- ==========================================
-- Columns used: Tenure
-- Query:
    SELECT
    CASE
        WHEN Tenure < 12 THEN '0–11 months (New)'
        WHEN Tenure BETWEEN 12 AND 24 THEN '12–24 months (Early)'
        WHEN Tenure BETWEEN 25 AND 48 THEN '25–48 months (Mid)'
        ELSE '49+ months (Loyal)'
    END AS tenure_bucket,

    COUNT(*) AS total_customers,

    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS pct_of_total

FROM customer_churn

GROUP BY
    CASE
        WHEN Tenure < 12 THEN '0–11 months (New)'
        WHEN Tenure BETWEEN 12 AND 24 THEN '12–24 months (Early)'
        WHEN Tenure BETWEEN 25 AND 48 THEN '25–48 months (Mid)'
        ELSE '49+ months (Loyal)'
    END

ORDER BY MIN(Tenure);
-- ==========================================

-- ==========================================
-- 6. Distribution of monthly charges.
-- ==========================================
-- Columns used: MonthlyCharges
-- Query:
    SELECT
    CASE
        WHEN MonthlyCharges < 30 THEN 'Low'
        WHEN MonthlyCharges BETWEEN 30 AND 70 THEN 'Medium'
        ELSE 'High'
    END AS charge_category,

    COUNT(*) AS total_customers

FROM customer_churn

GROUP BY
    CASE
        WHEN MonthlyCharges < 30 THEN 'Low'
        WHEN MonthlyCharges BETWEEN 30 AND 70 THEN 'Medium'
        ELSE 'High'
    END;
-- ==========================================

-- ==========================================
-- 7. Distribution of total charges.
-- ==========================================
-- Columns used: TotalCharges
-- Query:
   SELECT
    CASE
        WHEN TotalCharges < 1000 THEN 'Low'
        WHEN TotalCharges BETWEEN 1000 AND 5000 THEN 'Medium'
        ELSE 'High'
    END AS revenue_category,

    COUNT(*) AS total_customers

FROM customer_churn

GROUP BY
    CASE
        WHEN TotalCharges < 1000 THEN 'Low'
        WHEN TotalCharges BETWEEN 1000 AND 5000 THEN 'Medium'
        ELSE 'High'
    END;
-- ==========================================

-- ==========================================
-- 8. Distribution of Tech Support adoption.
-- ==========================================
-- columns used: TechSupport
-- Query:
    SELECT TechSupport,
        COUNT(*) AS total_customers
    FROM customer_churn
    GROUP BY TechSupport;
-- ==========================================

-- ==========================================
-- 9. Distribution of Online Security adoption.
-- ==========================================
-- Columns used: OnlineSecurity
-- Query:
    SELECT OnlineSecurity,
        COUNT(*) AS total_customers
    FROM customer_churn
    GROUP BY OnlineSecurity;
-- ==========================================

-- ==========================================
-- 10. Distribution of Senior Citizens.
-- ==========================================
-- Columns used: SeniorCitizen
-- Query:
    SELECT SeniorCitizen,
        COUNT(*) AS total_customers
    FROM customer_churn
    GROUP BY SeniorCitizen;
-- ==========================================


-- SECTION 6: Bivariate Analysis
-- ==========================================
-- 1. Relationship between contract type and churn.
-- ==========================================
-- Columns used: Contract,Churn
-- Query: 
    SELECT Contract,
 
        COUNT(*) AS total_customers,
         
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS churn_rate
 
     FROM customer_churn
 
     GROUP BY Contract;
-- ==========================================

-- ==========================================
-- 2. Relationship between internet service type and churn.
-- ==========================================
-- Columns used: InternetService,Churn
-- Query:
    SELECT InternetService,
     
       COUNT(*) AS total_customers,
 
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS churn_rate
         
    FROM customer_churn
     
    GROUP BY InternetService;
-- ==========================================

-- ==========================================
-- 3. Relationship between payment method and churn.
-- ==========================================
-- Columns used: PaymentMethod,Churn
-- Query:
     SELECT PaymentMethod,
      
        COUNT(*) AS total_customers,
 
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS churn_rate
         
    FROM customer_churn
     
    GROUP BY PaymentMethod;
-- ==========================================

-- ==========================================
-- 4. Relationship between Tech Support and churn.
-- ==========================================
-- Columns used: TechSupport,Churn
-- Query:
    SELECT TechSupport,
 
        COUNT(*) AS total_customers,
         
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS churn_rate
         
   FROM customer_churn
   
   GROUP BY TechSupport;
-- ==========================================

-- ==========================================
-- 5. Relationship between Online Security and churn.
-- ==========================================
-- Columns used: OnlineSecurity,Churn
-- Query:
     SELECT OnlineSecurity,
 
        COUNT(*) AS total_customers,
         
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS churn_rate
         
    FROM customer_churn
 
    GROUP BY OnlineSecurity;
-- ==========================================

-- ==========================================
-- 6. Relationship between partner status and churn.
-- ==========================================
-- Columns used: Partner,Churn
-- Query:
      SELECT Partner,
 
        COUNT(*) AS total_customers,
         
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS churn_rate
         
    FROM customer_churn
     
    GROUP BY Partner;
-- ==========================================

-- ==========================================
-- 7. Relationship between dependent status and churn.
-- ==========================================
-- Columns used: Dependents,Churn
-- Query:
      SELECT Dependents,
       
        COUNT(*) AS total_customers,
 
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS churn_rate
         
    FROM customer_churn
  
    GROUP BY Dependents;
-- ==========================================

-- ==========================================
-- 8. Relationship between monthly charges and churn.
-- ==========================================
-- Columns used: MonthlyCharges,Churn
-- Query:
     SELECT
    CASE
        WHEN MonthlyCharges < 30 THEN 'Low Charges'
        WHEN MonthlyCharges BETWEEN 30 AND 70 THEN 'Medium Charges'
        ELSE 'High Charges'
    END AS charge_segment,

    COUNT(*) AS total_customers,

    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS churn_rate

FROM customer_churn

GROUP BY
    CASE
        WHEN MonthlyCharges < 30 THEN 'Low Charges'
        WHEN MonthlyCharges BETWEEN 30 AND 70 THEN 'Medium Charges'
        ELSE 'High Charges'
    END;
-- ==========================================

-- ==========================================
-- 9. Relationship between tenure and churn.
-- ==========================================
-- Columns used: Tenure,Churn
-- Query:
     SELECT
    CASE
        WHEN Tenure < 12 THEN 'New Customers'
        WHEN Tenure BETWEEN 12 AND 36 THEN 'Medium Tenure'
        ELSE 'Long Tenure'
    END AS tenure_segment,

    COUNT(*) AS total_customers,

    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS churn_rate

FROM customer_churn

GROUP BY
    CASE
        WHEN Tenure < 12 THEN 'New Customers'
        WHEN Tenure BETWEEN 12 AND 36 THEN 'Medium Tenure'
        ELSE 'Long Tenure'
    END;
-- ==========================================

-- ==========================================
-- 10. Relationship between senior citizen status and churn.
-- ==========================================
-- Columns used: SeniorCitizen,Churn
-- Query:
     SELECT SeniorCitizen,
 
        COUNT(*) AS total_customers,
         
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS churn_rate
 
    FROM customer_churn
     
    GROUP BY SeniorCitizen;
-- ==========================================


-- SECTION 7: Multivariate Analysis
-- ===========================================
-- 1. Churn across contract type and internet service type.
-- ===========================================
-- Columns used: Contract,InternetService,Churn
-- Query:
     SELECT Contract,
        InternetService,
         
        COUNT(*) AS total_customers,
         
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS churn_rate
 
    FROM customer_churn
 
    GROUP BY Contract,
          InternetService;
-- ===========================================

-- ===========================================
-- 2. Revenue and Churn across contract types.
-- ===========================================
-- Columns used: Contract,TotalCharges,Churn
-- Query:
      SELECT Contract,
 
        ROUND(
         SUM(TotalCharges)
        ,2
         ) AS total_revenue,
 
        ROUND(
         SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*)
        ,2
        ) AS churn_rate
         
   FROM customer_churn
  
   GROUP BY Contract;
-- ===========================================

-- ===========================================
-- 3. Churn across payment method and contract type.
-- ===========================================
-- Columns used: PaymentMethod,Contract,Churn
-- Query:
    SELECT PaymentMethod,
        Contract,
 
        COUNT(*) AS total_customers,
 
        ROUND(
         SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS churn_rate
 
   FROM customer_churn
 
   GROUP BY PaymentMethod,
          Contract;
-- ===========================================

-- ===========================================
-- 4. Churn across Tech Support and internet service type.
-- ===========================================
-- Columns used: TechSupport,InternetService,Churn 
-- Query:
      SELECT TechSupport,
        InternetService,
 
        COUNT(*) AS total_customers,
 
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS churn_rate
 
     FROM customer_churn
 
     GROUP BY TechSupport,
          InternetService;
-- ===========================================

-- ===========================================
-- 5. Churn across Online Security and Online Backup services.
-- ===========================================
-- Columns used: OnlineSecurity,OnlineBackup,Churn
-- Query:
     SELECT OnlineSecurity,
        OnlineBackup,
 
        COUNT(*) AS total_customers,
 
        ROUND(
         SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
         ) AS churn_rate
 
    FROM customer_churn
  
    GROUP BY OnlineSecurity,
           OnlineBackup;
-- ===========================================

-- ===========================================
-- 6. Churn across partner and dependent status.
-- ===========================================
-- Columns used: Partner,Dependents,Churn
-- Query:
    SELECT Partner,
        Dependents,
         
        COUNT(*) AS total_customers,
 
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
         *100.0/COUNT(*),2
        ) AS churn_rate
 
    FROM customer_churn
  
    GROUP BY Partner,
          Dependents;
-- ===========================================

-- ===========================================
-- 7. Churn across senior citizen status and contract type.
-- ===========================================
-- Columns used: SeniorCitizen,Contract,Churn 
-- Query:
      SELECT SeniorCitizen,
        Contract,
 
        COUNT(*) AS total_customers,
 
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS churn_rate
 
    FROM customer_churn
 
    GROUP BY SeniorCitizen,
          Contract;
-- ===========================================

-- ===========================================
-- 8. Churn across tenure and revenue segments.
-- ===========================================
-- Columns used: Tenure,TotalCharges,Churn 
-- Query:
      SELECT
    CASE
        WHEN Tenure < 12 THEN 'Low Tenure'
        WHEN Tenure BETWEEN 12 AND 36 THEN 'Medium Tenure'
        ELSE 'High Tenure'
    END AS tenure_segment,

    CASE
        WHEN TotalCharges < 1000 THEN 'Low Revenue'
        WHEN TotalCharges BETWEEN 1000 AND 5000 THEN 'Medium Revenue'
        ELSE 'High Revenue'
    END AS revenue_segment,

    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS churn_rate

FROM customer_churn

GROUP BY
    CASE
        WHEN Tenure < 12 THEN 'Low Tenure'
        WHEN Tenure BETWEEN 12 AND 36 THEN 'Medium Tenure'
        ELSE 'High Tenure'
    END,
    CASE
        WHEN TotalCharges < 1000 THEN 'Low Revenue'
        WHEN TotalCharges BETWEEN 1000 AND 5000 THEN 'Medium Revenue'
        ELSE 'High Revenue'
    END;
-- ===========================================

-- ===========================================
-- 9. Churn across paperless billing and contract type.
-- ===========================================
-- Columns used: PaperlessBilling,Contract,Churn
-- Query:
     SELECT PaperlessBilling,
        Contract,
 
        COUNT(*) AS total_customers,
         
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
         ) AS churn_rate
 
    FROM customer_churn
     
    GROUP BY PaperlessBilling,
          Contract;
-- ===========================================

-- ===========================================
-- 10. Churn across different combinations of telecom services.
-- ===========================================
-- Columns used: PhoneService,InternetService,StreamingTV, StreamingMovies,Churn 
-- Query:
     SELECT PhoneService,
        InternetService,
        StreamingTV,
         StreamingMovies,
 
        COUNT(*) AS total_customers,
 
        ROUND(
         SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
        ) AS churn_rate
 
     FROM customer_churn
 
     GROUP BY PhoneService,
              InternetService,
              StreamingTV,
              StreamingMovies;			  
-- ===========================================


-- SECTION 8: CTE Problems
-- ===========================================
-- 1. Customers whose tenure is above the company average.
-- ===========================================
-- Columns used: CustomerID,Tenure
-- Query:
     WITH avg_tenure_cte AS
 (
     SELECT AVG(Tenure) AS avg_tenure
     FROM customer_churn
  )
 
 SELECT CustomerID,
        Tenure
 FROM customer_churn
 WHERE Tenure >
 (
     SELECT avg_tenure
     FROM avg_tenure_cte
 );
-- ===========================================

-- ===========================================
-- 2. Customers whose total charges are above the company average.
-- ===========================================
-- Columns used: CustomerID,TotalCharges
-- Query:
     WITH avg_revenue_cte AS
 (
      SELECT AVG(TotalCharges) AS avg_revenue
     FROM customer_churn
 )
  
 SELECT CustomerID,
        TotalCharges
 FROM customer_churn
 WHERE TotalCharges
 >
 (
     SELECT avg_revenue
     FROM avg_revenue_cte
 );
-- ===========================================

-- ===========================================
-- 3. Customers whose monthly charges are above the company average.
-- ===========================================
-- Columns used: CustomerID,MonthlyCharges
-- Query:
    WITH avg_monthly_cte AS
    (
    SELECT AVG(MonthlyCharges) AS avg_monthly_charge
    FROM customer_churn
    )

SELECT CustomerID,
       MonthlyCharges
FROM customer_churn
WHERE MonthlyCharges >
(
    SELECT avg_monthly_charge
    FROM avg_monthly_cte
);
-- ===========================================

-- ===========================================
-- 4. High-value customers who churned.
-- ===========================================
-- Columns used: CustomerID,TotalCharges,Churn 
-- Query:
     WITH high_value_customers AS
     (
     SELECT CustomerID,
            TotalCharges AS TotalCharges
 
     FROM customer_churn
 
     WHERE TotalCharges
     >
     (SELECT AVG(TotalCharges)
         FROM customer_churn
     )
      )
 
 SELECT h.CustomerID,
        h.TotalCharges
 
 FROM high_value_customers h
 
 JOIN customer_churn c
 ON h.CustomerID = c.CustomerID
 
 WHERE c.Churn='Yes';
-- ===========================================

-- ===========================================
-- 5. Customer value segments and Churn rate for each segment.
-- ===========================================
-- Columns used: CustomerID,TotalCharges,Churn 
-- Query:
     WITH value_segment AS
     (
     SELECT CustomerID,
 
            CASE
                 WHEN TotalCharges >= 5000 THEN 'High Value'
                 WHEN TotalCharges >= 2000 THEN 'Medium Value'
                 ELSE 'Low Value'
            END AS customer_segment,
  
            Churn
 
     FROM customer_churn
     )
 
     SELECT customer_segment,
 
        COUNT(*) AS total_customers,
 
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
         ) AS churn_rate
 
      FROM value_segment
 
      GROUP BY customer_segment;
-- ===========================================

-- ===========================================
-- 6. Revenue Distribution Across Risk Segments
-- ===========================================
-- Columns used: CustomerID,Contract,Tenure,TotalCharges
-- Query:
     WITH risk_segment AS
    (
     SELECT CustomerID,
            TotalCharges,
 
            CASE
                 WHEN Contract='Month-to-month'
                      AND Tenure < 12
                 THEN 'High Risk'
 
                 WHEN Tenure < 24
                 THEN 'Medium Risk'
 
                 ELSE 'Low Risk'
            END AS risk_category
 
     FROM customer_churn
     )
 
     SELECT risk_category,
 
        ROUND(
         SUM(
        TotalCharges
         )
        ,2
          ) AS revenue_at_risk
 
    FROM risk_segment
 
    GROUP BY risk_category;
-- ===========================================

-- ===========================================
-- 7. Contract-level churn rates with the overall company churn rate.
-- ===========================================
-- Columns used: Contract,Churn 
-- Query:
     WITH company_churn AS
    (
      SELECT
     ROUND(
     SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
      *100.0/COUNT(*),2
     ) AS overall_churn_rate
 
     FROM customer_churn
    )
 
    SELECT Contract,
 
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
        *100.0/COUNT(*),2
         ) AS contract_churn_rate,
          
         (SELECT overall_churn_rate
         FROM company_churn)
         AS company_churn_rate
 
    FROM customer_churn
 
    GROUP BY Contract;
-- ===========================================

-- ===========================================
-- 8. Revenue at risk for each contract type.
-- ===========================================
-- Columns used: Contract,TotalCharges,Churn 
-- Query:
     WITH churned_customers AS
    (
     SELECT Contract,
            TotalCharges
             
     FROM customer_churn
 
     WHERE Churn='Yes'
     )
 
     SELECT Contract,
 
        ROUND(
        SUM(
        TotalCharges
        )
       ,2
         ) AS revenue_at_risk
 
    FROM churned_customers
 
    GROUP BY Contract;
-- ===========================================

-- ===========================================
-- 9. Customer retention priority model.
-- ===========================================
-- Columns used: CustomerID,Contract,Tenure,MonthlyCharges
-- Query:
      WITH retention_priority AS
    (
     SELECT CustomerID,
 
            CASE
                 WHEN Contract='Month-to-month'
                      AND Tenure < 12
                      AND MonthlyCharges > 80
                 THEN 'Priority 1'
                  
                 WHEN Tenure < 24
                  THEN 'Priority 2'
 
                 ELSE 'Priority 3'
            END AS retention_priority
 
     FROM customer_churn
     )
 
     SELECT *
     FROM retention_priority;
-- ===========================================

-- ===========================================
-- 10. Customer lifetime value categories over Churn within each category.
-- ===========================================
-- Columns used: CustomerID,TotalCharges,Churn 
-- Query:
      WITH clv_segment AS
     (
       SELECT CustomerID,
        
            CASE
                 WHEN TotalCharges >= 5000 THEN 'High CLV'
                 WHEN TotalCharges >= 2000 THEN 'Medium CLV'
                  ELSE 'Low CLV'
            END AS clv_category,
 
             Churn
 
     FROM customer_churn
      )
 
 SELECT clv_category,
 
        COUNT(*) AS total_customers,
 
        ROUND(
        SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END)
         *100.0/COUNT(*),2
        ) AS churn_rate
 
    FROM clv_segment
 
    GROUP BY clv_category;
-- ===========================================


-- SECTION 9: Window Functions Problems
-- ===========================================
-- 1. Customers by total charges.
-- ===========================================
-- Columns used: CustomerID,TotalCharges
-- Query:
     SELECT CustomerID,
        TotalCharges,
 
        RANK() OVER
        (
            ORDER BY TotalCharges DESC
        ) AS revenue_rank
 
 FROM customer_churn;
-- ===========================================

-- ===========================================
-- 2. Customers within each contract type based on total charges.
-- ===========================================
-- Columns used: CustomerID,Contract,TotalCharges
-- Query:
     SELECT CustomerID,
        Contract,
        TotalCharges,
 
        RANK() OVER
        (
            PARTITION BY Contract
            ORDER BY TotalCharges DESC
        ) AS contract_rank 
 
     FROM customer_churn;
-- ===========================================

-- ===========================================
-- 3. AssignING row numbers to customers within each contract type.
-- ===========================================
-- Columns used: CustomerID,Contract,TotalCharges
-- Query:
     SELECT CustomerID,
        Contract,
        TotalCharges,
 
        ROW_NUMBER() OVER
        (
            PARTITION BY Contract
            ORDER BY TotalCharges DESC
        ) AS row_num
 
      FROM customer_churn;
-- ===========================================

-- ===========================================
-- 4. Dividing customers into revenue tiers.
-- ===========================================
-- Columns used: CustomerID,TotalCharges
-- Query:
    SELECT CustomerID,
         TotalCharges,
 
        NTILE(4) OVER
        (
            ORDER BY TotalCharges DESC
        ) AS revenue_tier
 
     FROM customer_churn;
-- ===========================================

-- ===========================================
-- 5. Comparing customer's revenue with the previous customer's revenue.
-- ===========================================
-- Columns used: CustomerID,TotalCharges
-- Query:
      SELECT CustomerID,
        TotalCharges,
 
        LAG(
        TotalCharges
         ) OVER
         (
            ORDER BY TotalCharges DESC
        ) AS previous_customer_revenue
 
     FROM customer_churn;
-- ===========================================

-- ===========================================
-- 6. Comparing customer's revenue with the next customer's revenue.
-- ===========================================
-- Columns used: CustomerID,TotalCharges
-- Query:
     SELECT CustomerID,
         TotalCharges,
 
        LEAD(
        TotalCharges
        ) OVER
        (
            ORDER BY TotalCharges DESC
        ) AS next_customer_revenue
 
     FROM customer_churn;
-- ===========================================

-- ===========================================
-- 7. Highest-revenue customer within each contract type.
-- ===========================================
-- Columns used: CustomerID,Contract,TotalCharges
-- Query:
       WITH ranked_customers AS
 (
     SELECT CustomerID,
            Contract,
            TotalCharges,
         ROW_NUMBER() OVER
 (
     PARTITION BY Contract
     ORDER BY TotalCharges DESC
 ) AS rn
     FROM customer_churn
 )
  
  SELECT CustomerID,
        Contract,
        TotalCharges
 
  FROM ranked_customers
 
  WHERE rn = 1;
-- ===========================================

-- ===========================================
-- 8. Lowest-revenue customer within each contract type.
-- ===========================================
-- Columns used: CustomerID,Contract,TotalCharges
-- Query:
      WITH ranked_customers AS
 (
     SELECT CustomerID,
            Contract,
            TotalCharges,
             
         ROW_NUMBER() OVER
 (
     PARTITION BY Contract
     ORDER BY TotalCharges ASC
  ) AS rn
   
     FROM customer_churn
  )
 
   SELECT CustomerID,
        Contract,
        TotalCharges
         
 FROM ranked_customers
 
 WHERE rn = 1;
-- ===========================================

-- ===========================================
-- 9. Running total of revenue across customers.
-- ===========================================
-- Columns used: CustomerID,TotalCharges
-- Query:
      SELECT
    CustomerID,
    Tenure,
    TotalCharges,

    SUM(TotalCharges) OVER (
        ORDER BY TotalCharges ASC, CustomerID ASC
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS running_revenue

FROM customer_churn

ORDER BY TotalCharges ASC;
-- ===========================================

-- ===========================================
-- 10. Compare each customer's revenue with the average revenue of their contract type.
-- ===========================================
-- Columns used: CustomerID,Contract,TotalCharges
-- Query:
      SELECT CustomerID,
        Contract,
 
        TotalCharges
        AS TotalCharges,
 
        ROUND(
        AVG(
        TotalCharges
        ) OVER
        (
            PARTITION BY Contract
        )
        ,2
        ) AS contract_avg_revenue,
 
        ROUND(
        TotalCharges
        -
        AVG(
        TotalCharges
        ) OVER
        (
            PARTITION BY Contract
        )
        ,2
        ) AS difference_from_contract_avg
         
 FROM customer_churn;
-- ===========================================
/*

-- =====================================================
-- FINAL FINDINGS
-- =====================================================

-- 1. Customer churn varies significantly across contract types,
-- indicating that customer commitment level influences retention.

-- 2. Churn behavior differs across payment methods,
-- suggesting payment preferences may be associated with customer loyalty.

-- 3. Internet service type plays a role in churn patterns,
-- making service-specific retention strategies important.

-- 4. Customers without additional support-related services
-- (such as Tech Support and Online Security) tend to represent an important churn-risk segment.

-- 5. Customer tenure is strongly related to retention behavior,
-- with newer customers generally requiring greater retention focus.

-- 6. Revenue loss due to churn represents a measurable business risk,
-- making high-value customer retention a priority.

-- 7. Customer segmentation based on tenure, monthly charges,
-- and total revenue helps identify high-risk customer groups.

-- 8. Window-function analysis helps identify top customers,
-- cumulative revenue contribution, and customer ranking patterns.

-- =====================================================
-- BUSINESS RECOMMENDATIONS
-- =====================================================

-- 1. Prioritize retention campaigns for high-risk customer segments.

-- 2. Improve onboarding programs for newer customers.

-- 3. Promote value-added services such as Tech Support
-- and Online Security to improve retention.

-- 4. Monitor churn trends by contract type and payment method.

-- 5. Develop a churn prediction dashboard using the key
-- variables identified in this analysis.

-- 6. Focus retention efforts on high-revenue customers
-- to minimize revenue loss.